---
title: "Literature Review"
output: html_document
---

In Mortensen et al. (2019), the provision of trending norm information for behavioral change was established as more effective than simply providing descriptive norm information. This is because messages that convey that only a numerical minority of people perform a desirable behavior does not encourage conformity as much as normative messages that convey a minority norm is increasing in popularity. A “trend effect” occurs when people perceive behavior the way they do items in motion- just as items moving in a certain direction are expected to continue moving in that direction so does trending behavior. This theory is based on cognitive and neurological mechanisms attributed to ‘psychological momentum’, which is described as an influential force which lays out the foundation and direction of an expected behavior (Markman & Guenther, 2007), making it also more salient and important (Erlandsson, Hohle, Løhre, & Västfjäll, 2018). In Erlandsson et al. (2018) researchers examined how people's behaviors are influenced by directional trends. Participants were given mortality statistics about different types of cancers where data was shown as either a flat number or on an upward or downward trajectory. Results showed that participants allocated more money to cancers that they perceived as trending negatively. Another perspective on trending effects reveals that people believe that others are putting effort into trending behavior, which compels them to “pre-conform”(Sparkman & Walton, 2017). Some research suggests that beliefs play a dominant role in changed behavior, such as in Engler et al. (2008) where participants’ overestimated the amount their peers cheat, so that perceptions of what others do gives them a “license” to behave as they do. Research by Abeler and Raymond (2019) demonstrated that changes in beliefs of what others are doing does not affect aversion for anti-social behavior but rather an individual’s preference for being perceived as honest. This suggests that what might appear as social conformity is actually behavior based on a desire to self-perceive as being honest relative to others, rather than a re-evaluation for the appropriateness of a behavior, as in a social norm. Other theories and findings suggest that people care about keeping a moral self-image (Fischbacher & Heusi, 2008; Jiang, 2013), and they only cheat to the extent that their moral image is maintained (Ariely, 2012). This suggests a limited impact of social conformity due to norm intervention. Yet, in Rauhut’s (2013) study, researchers investigated whether the provision of information alone, or rather eliciting beliefs first about others’ norm violations, will increase or decrease people’s own norm transgressions. Results show that informed people who under-estimated others’ lying subsequently increased their own lying by twice as much in comparison to people without information about others’ lies. Furthermore, informed individuals who initially overestimated others’ lying behavior, later decreased their own lying by more than half in comparison to people without information about others’ lies. Hence, the direction of the dynamics, the spreading of normative decay and restoring of norm adherence, is crucially dependent on subjects’ beliefs about the directions of others’ behaviors.


