---
title: " Discussion and Conclusion"
output: html_document
---
In recent years, there has been a growing interest in how norm-nudges, such as leveraging the trend effect, can be used to elicit socially desirable behavior. Our research seeks to contribute to the existing social norm literature by attempting to answer whether, and to what extent, upward and downward trending information about social norms influences behavior. The study’s main prediction was that social norm interventions showing trends in University of Pennsylvania student’s academic integrity would be more effective at changing behavior than interventions using similar information but with static framing. A second prediction of our study was that interventions with an upward trend should be more effective than interventions with a downward trend.

We presented participants with the intervention’s statements at the midway point during a 20-round dice game, in which participants were incentivized to lie about the numbers they roll, in order to win more tickets for a gift card. However, the results of our study indicate that neither of our hypotheses were supported by the data, which suggests that our trending norm interventions did not affect players’ behavior during the experiment.

One possible explanation for this study’s null results could be that the interventions were ineffective due to players’ perceptions that their game play was being observed by the experimenters. Researchers for the current study had the ability to observe each participant’s response for each round of the game when the game was completed; however, players were given no indication that this would be the case. Despite lacking direct knowledge that their rounds were being monitored, approximately 70% of the participants in our study believed their game play was being monitored, and this subjective perception may have acted as a deterrent for players to act in a dishonest manner. Participants’ perceptions of whether their responses were private or not may have contributed to the study’s high levels of honesty even after the interventions because participants were afraid of possible consequences of being caught in a lie (Kajackaite & Gneezy, 2017). Prior research (Dimant et al., 2019) has revealed that if there is a risk for being exposed as a “cheater”, participants will curb lying behavior even when informed of others’ behavior. Although our analysis showed no significant differences between players who perceived they were being watched vs. players who did not, we can’t rule out the possibility lying behavior was suppressed due to player fears of being exposed as a cheater.  

A second explanation for the lack of a trend effect relays back to the conditions necessary for a trend to be perceived. That is, people need to be made aware of two data points (Hohle & Teigen, 2015) over time in order to recognize that a trend is actually occurring. Our experiment failed to provide these data points and therefore might not have fulfilled the necessary benchmark for meeting a trend effect. Future studies could utilize two or more data points to better ensure that the trend effect is salient. 

A third potential cause for the null effects of our study could be related to the intervention statements and the social network those statements were referencing. Recent research indicates that the salience of the norm intervention is critical (Zhao, Dong, & Yu, 2019). While the majority of the participants in this study were recruited on the University of Pennsylvania campus, the study was not solely limited to students. This may have weakened the effect of our norm interventions, which referenced the academic integrity of University of Pennsylvania students. The intervention statements used in our study may have been lacking in social proximity for study participants who were not students at the University of Pennsylvania, and thus the intervention statements were not salient enough to induce conformity to the social norm. Since conformity to norms is reinforced by the threat of social disapproval and punishment (Bicchieri, 2017), it is a possibility that non-students simply did not care about the social norms they were presented with during the dice game. Unfortunately, the authors of the current study have no way of determining if non-student participants had any influence on the results of the study because this demographic data was not asked in the survey.   Future explorations of this topic could tailor interventions to ensure relevance to the subject pool, potentially by utilizing statements about the dice game itself rather than referring to broader cheating behaviors.

An extension to further explore the effect of trending norms could include asking participants a series of questions pertaining to their cultural background. Different cultural backgrounds could influence whether and by how much people play honestly or dishonestly in the dice game, and how they receive and react to trending social norm information. Previous research (Gachter & Schulz, 2016) shows that cultural characteristics, such as individualistic or collectivistic, might also strongly influence individuals’ decision to cheat due to differences in the perceived scope of moral responsibilities and interestingly that there was a positive correlation between honesty and prevalence of rule violations at the country-level.
Finally, a limitation of our analysis was the relatively small number of participants who only lied some of the time. 78% of participants were honest in their reports for every roll and 9% lied at every opportunity, leaving only 13% of participants who lied occasionally and were likely to be open to the influence of normative data. Further studies should increase sample size accordingly, increase the incentives to lie, and consider eliciting further information from the participants, such as whether they were aware that they could cheat, in the post-game survey.

Although we were unable to find statistically significant results, we believe that the influence of trending norms requires further exploration. Our study was limited in scope and statistical power, and future research could offer new insights which may hold significant implications for policymakers and behavioral scientists alike.

